version: "3"
services:
  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./web/loadbalancer.conf:/etc/nginx/conf.d/loadbalancer.conf
    ports:
      - 80:80
    networks:
      - monolith_nw
    depends_on: 
      - app

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - monolith_nw

  app2:
    container_name: app2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    depends_on:
      - db
    networks:
      - monolith_nw

  db:
    container_name: db
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - monolith_data:/var/lib/postgresql/data
    networks:
      - monolith_nw

volumes:
  monolith_data:
networks:
  monolith_nw:
