version: '3'
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile_web
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile_db
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
